In [2]:
import numpy as np
import gurobipy as gp
from gurobipy import GRB

In [46]:
# RMP
N = 3
M = 3
patterns = np.matrix([[2, 0, 0], [0, 1, 0], [0, 0, 1]])
print(patterns)
c = np.array([5, 5, 5])
rhs = np.array([30, 20, 40])
print(c)
model = gp.Model("cutting stock")
x = model.addVars(N, vtype=GRB.INTEGER, name="x")
cons = model.addConstrs((gp.quicksum(patterns[i, j] * x[j] for j in range(3)) >= rhs[i] for i in range(3)))
model.setObjective(gp.quicksum(c[i]*x[i] for i in range(3)))
model.write("output.lp")

[[2 0 0]
 [0 1 0]
 [0 0 1]]
[5 5 5]


In [47]:
model.optimize()

Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 3 rows, 3 columns and 3 nonzeros
Model fingerprint: 0x9d89c5da
Variable types: 0 continuous, 3 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [5e+00, 5e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 4e+01]
Found heuristic solution: objective 375.0000000
Presolve removed 3 rows and 3 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 1: 375 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.750000000000e+02, best bound 3.750000000000e+02, gap 0.0000%


In [48]:
for v in model.getVars():
    print("%s = %g" % (v.VarName, v.x), end = " ")
print()
print("optimal: ", model.ObjVal)

x[0] = 15 x[1] = 20 x[2] = 40 
optimal:  375.0


In [53]:
model2 = gp.Model("cutting stock continous")
y = model2.addVars(N, vtype=GRB.CONTINUOUS, name="y")
cons = model2.addConstrs((gp.quicksum(patterns[i, j] * y[j] for j in range(3)) >= rhs[i] for i in range(3)))
model2.setObjective(gp.quicksum(c[i]*y[i] for i in range(3)))
model2.optimize()

Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 3 rows, 3 columns and 3 nonzeros
Model fingerprint: 0x6021a812
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [5e+00, 5e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 4e+01]
Presolve removed 3 rows and 3 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    3.7500000e+02   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds (0.00 work units)
Optimal objective  3.750000000e+02
shadow:  [2.5, 5.0, 5.0]
